### ISSUE TITLE
nghttpx http2 proxy after starting some time to stay in "Waiting for proxy tunnel response"

### ISSUE THREAD

**Issue by fourstring** [tatsuhiro-t/nghttp2#276] opened 2015-06-29 06:17 UTC
I set up a HTTP2 proxy, but a period of time (several tens of minutes), will remain in the "Waiting for proxy tunnel response", I must restart nghttpx to return to normal
And usually this happens when I use it to watch YouTube
My browser is chrome 43, the configuration file as follows:

http2-max-concurrent-streams = 4000
workers = 128
frontend = 0.0.0.0,443
backend = 127.0.0.1,3128
private-key-file = /path/to/key
certificate-file = /path/to/crt
http2-proxy = yes
add-x-forwarded-for = no
no-via = yes
no-ocsp = yes
npn-list = spdy / 3.1, h2
tls-proto-list = TLSv1.2

**Comment by tatsuhiro-t** [comment] 2015-06-29 12:15
This is known issue, and was reported in https://github.com/tatsuhiro-t/nghttp2/issues/262#issuecomment-114728957, and now tracked in #267.

As for your configuration, you should set workers to the number of cores.  Also npn-list's `spdy / 3.1` should be `spdy/3.1`. http2-max-concurrent-streams is not so helpful to set this high. 100 seems to be enough for my experience.  Larger value is not necessarily better.

**Comment by tatsuhiro-t** [comment] 2015-07-04 02:15
These chrome bugs may be the cause:
https://code.google.com/p/chromium/issues/detail?id=464875
https://code.google.com/p/chromium/issues/detail?id=473259

In short, they are flow control issue on chrome side.  They say Chrome 44 may have short term workaround.

Using Firefox may be a good workaround for a while, if you can switch to Firefox.. It has different flow control approach.

**Comment by tatsuhiro-t** [comment] 2015-07-04 02:36
Closing as duplicate of #267.

**Closed by tatsuhiro-t** 2015-07-04 02:36 UTC
