### ISSUE TITLE
Run h2load for a duration

### ISSUE THREAD

**Issue by bharatkrishna** [tatsuhiro-t/nghttp2#516] opened 2016-02-16 21:49 UTC
I would need to run h2load for a particular duration. Could a parameter be added?

**Comment by shukitchan** [comment] 2016-02-17 02:15
you can view #463 for some suggestions and tips.

**Comment by tatsuhiro-t** [comment] 2016-02-17 15:08
Closing as duplicate of #463

**Closed by tatsuhiro-t** 2016-02-17 15:08 UTC
