### ISSUE TITLE
build issues with gcc6

### ISSUE THREAD

**Issue by plusky** [tatsuhiro-t/nghttp2#493] opened 2016-01-29 18:54 UTC
It seems that in order to build succesfully with gcc6 following patch is necessary:
```patch
--- src/template.h.orig	2016-01-28 15:30:56.549094834 +0100
+++ src/template.h	2016-01-28 15:42:13.188970636 +0100
@@ -37,6 +37,9 @@
 
 namespace nghttp2 {
 
+#if __cplusplus > 201103L
+using std::make_unique;
+#else
 template <typename T, typename... U>
 typename std::enable_if<!std::is_array<T>::value, std::unique_ptr<T>>::type
 make_unique(U &&... u) {
@@ -48,6 +51,7 @@
 make_unique(size_t size) {
   return std::unique_ptr<T>(new typename std::remove_extent<T>::type[size]());
 }
+#endif
 
 // std::forward is constexpr since C++14
 template <typename... T>
```
See also:
https://build.opensuse.org/package/view_file/devel:libraries:c_c++/nghttp2/nghttp2-c++14.patch?expand=1

**Comment by tatsuhiro-t** [comment] 2016-01-30 09:38
Thank you.  This is caused by ADL.  Looks like gcc6 enables C++14 by default.

**Comment by tatsuhiro-t** [comment] 2016-01-30 09:43
Fix committed via 4e44fccdcf1d0fea6a8cd88916040e06fc75d9db

**Comment by thinred** [comment] 2016-02-05 08:45
This was also observed in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811995
Thanks for the fix!

**Comment by tatsuhiro-t** [comment] 2016-02-05 12:30
The fix will be available in the next release (later in this month).

**Closed by tatsuhiro-t** 2016-02-05 12:30 UTC
Labels: bug
