### ISSUE TITLE
Normal HTTP without HTTPS handler

### ISSUE THREAD

**Issue by mhf-ir** [tatsuhiro-t/nghttp2#338] opened 2015-08-28 15:51 UTC
```
root@114309ffbec9:~# nghttpx -f*,80 -b127.0.0.1,8080 
Usage: nghttpx [OPTIONS]... [<PRIVATE_KEY> <CERT>]
A reverse proxy for HTTP/2, HTTP/1 and SPDY.
28/Aug/2015:15:50:50 +0000 PID188 [FATAL] shrpx.cc:2457 Too few arguments
```

```
root@114309ffbec9:~# nghttpx -v
nghttpx nghttp2/1.2.2-DEV
```

**Comment by tatsuhiro-t** [comment] 2015-08-28 15:57
Use --frontend-no-tls option.

**Comment by mhf-ir** [comment] 2015-09-05 21:42
i think i have problem using nginx backed webserver.
nginx works well but nghttpx give me 503:

```
root@205ed3896d42:/tmp# wget --spider localhost:8080
converted 'http://localhost:8080' (ANSI_X3.4-1968) -> 'http://localhost:8080' (UTF-8)
Spider mode enabled. Check if remote file exists.
--2015-09-05 21:25:04--  http://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Remote file exists and could contain further links,
but recursion is disabled -- not retrieving.

root@205ed3896d42:/tmp# nghttpx --frontend-no-tls -f*,80 -blocalhost,8080
05/Sep/2015:21:25:16 +0000 PID552 [NOTICE] Listening on ::, port 80
05/Sep/2015:21:25:16 +0000 PID552 [NOTICE] Listening on 0.0.0.0, port 80
^Z
[1]+  Stopped                 nghttpx --frontend-no-tls -f*,80 -blocalhost,8080
root@205ed3896d42:/tmp# bg
[1]+ nghttpx --frontend-no-tls -f*,80 -blocalhost,8080 &
root@205ed3896d42:/tmp# wget --spider localhost     
converted 'http://localhost' (ANSI_X3.4-1968) -> 'http://localhost' (UTF-8)
Spider mode enabled. Check if remote file exists.
--2015-09-05 21:25:33--  http://localhost/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
Remote file does not exist -- broken link!!!

root@205ed3896d42:/tmp# nghttpx -v
nghttpx nghttp2/1.3.1-DEV
```

**Comment by mhf-ir** [comment] 2015-09-05 21:43
sorry problem solved. it's localhost by docker container sorry. it's works well.

**Comment by mhf-ir** [comment] 2015-09-05 22:01
this is my proxy command
```
nghttpx --client --backend-no-tls --frontend-no-tls -f*,80 -b127.0.0.1,8080
05/Sep/2015:21:42:38 +0000 PID567 [NOTICE] Listening on ::, port 80
05/Sep/2015:21:42:38 +0000 PID567 [NOTICE] Listening on 0.0.0.0, port 80
```

it's worked but no data recived tested by firefox response `The connection was reset` and wget said 

```
wget --spider http://192.168.56.150/
Spider mode enabled. Check if remote file exists.
--2015-09-06 02:28:51--  http://192.168.56.150/
Connecting to 192.168.56.150:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
```

**Comment by tatsuhiro-t** [comment] 2015-09-06 04:33
I could not reproduce this.
--client requires HTTP/2 backend.  Please make sure that backend is HTTP/2 server without TLS.

**Comment by mhf-ir** [comment] 2015-09-06 05:38
backend is nginx and not http 2. i want to upgrade client http1 to http2 cause i use --client.

```

--client

    Accept HTTP/2 and HTTP/1.1 without SSL/TLS. The incoming HTTP/1.1 connection can be upgraded to HTTP/2 connection through HTTP Upgrade. The protocol to the backend is HTTP/2. To use nghttpx as a forward proxy, use -p option instead.

```

**Comment by tatsuhiro-t** [comment] 2015-09-06 06:09
All modern browsers support HTTP/2 over TLS only at the time of this writing.
For reverse proxying use case, use default mode (i.e., not specify --client)

**Comment by tatsuhiro-t** [comment] 2015-09-06 06:09
.. and without --frontend-no-tls.  You also need certificate of course.

**Comment by mhf-ir** [comment] 2015-09-06 06:33
oh, got it. thank you for support.

**Comment by tatsuhiro-t** [comment] 2015-09-21 10:53
Can we close this issue?

**Comment by mhf-ir** [comment] 2015-10-12 04:43
Of course, thank for your support. i use this awesome project on next production project. :+1:

**Closed** 2015-11-22 13:52 UTC
Labels: nghttpx
