### ISSUE TITLE
Proxy mode HTTP 1.1 request to HTTP/2 with --http2-bridge transmitting wrong

### ISSUE THREAD

**Issue by nergoza** [tatsuhiro-t/nghttp2#155] opened 2015-02-09 09:57 UTC
Hi,

I'm running HTTP 1.1 requests to the nghttpx proxy using --http2-proxy mode.
My clients sends 5 requests in 1 connection (persistence) and the proxy transmitting them to the HTTP/2 backend server like HTTP 1.1 requests just with h2-16 protocol.

In the backend server we see that instead of using the default max concurrent streams 100 it's setting the concurrent to max 1 stream and the backend needs to handle each requests individually 

I think that the proxy should ignore how the clients sends the requests and transmitting them only what the --max-concurrent-streams value is.

Tested it using browsers and also h2load tool

Thanks

**Comment by tatsuhiro-t** [comment] 2015-02-09 13:50
I tested locally and verified that streams are processed concurrently.
If you are using h2load, use -m option to set concurrency within connection:
```
$ h2load -n10 -m10 http://localhost:8080/
```

**Comment by nergoza** [comment] 2015-02-09 13:57
But h2load is an HTTP/2 client - my client is just 1.1 and cannot send it this way.
My Avalanche clients can send SPDY requests but I dont think there is a proxy mode that allow SPDY to HTTP/2

**Comment by tatsuhiro-t** [comment] 2015-02-09 14:28
You need to make multiple clients so that each one can send request to proxy, then as a whole several requests are in-flight concurrently.  You can see that using ab:
```
$ ab -n10 -c10 http://localhost:3000/
```

nghttpx supports SPDY frontend by linking spdylay library (https://github.com/tatsuhiro-t/spdylay) and --http2-bridge works with that, but you need enable TLS in frontend.

**Comment by nergoza** [comment] 2015-02-09 14:45
I tried to send SPDY over TLS and the proxy rejected the connection:

nghttpx --http2-bridge -LINFO -k  --http2-max-concurrent-streams=100 -f0.0.0.0,8080 -bspdy.ssltest.akamai.com,443 ../localhost.key ../localhost.crt 
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:1861 Resolving backend address
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:127 Address resolution for spdy.ssltest.akamai.com succeeded: 100.64.17.171
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:186 Unable to get IPv6 address for 0.0.0.0: Address family for hostname not supported
09/Feb/2015:16:42:01 +0200 PID30710 [NOTICE] Listening on 0.0.0.0, port 8080
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:474 renew ticket key
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:498 ticket keys generation done
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:500 name: 76ba1ee9dfd566c21e112671377158b9
09/Feb/2015:16:42:01 +0200 PID30710 [INFO] shrpx.cc:613 Entering event loop
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_connection_handler.cc:161 [LISTEN:0x7f9665829540] Accepted connection. fd=7
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_ssl.cc:173 [CLIENT_HANDLER:0x7f9665913000] encrypt session ticket key: 76ba1ee9dfd566c21e112671377158b9
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_client_handler.cc:205 [CLIENT_HANDLER:0x7f9665913000] SSL/TLS handshake completed
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_client_handler.cc:593 [CLIENT_HANDLER:0x7f9665913000] The negotiated next protocol: h2-16
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_client_handler.cc:395 [CLIENT_HANDLER:0x7f9665913000] invalid client connection header
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_client_handler.cc:519 [CLIENT_HANDLER:0x7f9665913000] Deleting
09/Feb/2015:16:44:29 +0200 PID30710 [INFO] shrpx_client_handler.cc:556 [CLIENT_HANDLER:0x7f9665913000] Deleted

**Comment by tatsuhiro-t** [comment] 2015-02-09 14:50
This is because client sends h2-16 in ALPN or NPN.  Make sure that client sends only spdy/3.1 as ALPN/NPN token, assuming client supports spdy/3.1.  Please note that spdy/3.1 and spdy/3 is different protocol.

**Comment by nergoza** [comment] 2015-02-09 14:53
the client sends SPDY 3 - it does not support 3.1

**Comment by tatsuhiro-t** [comment] 2015-02-09 15:21
Well, then use --npn-list=spdy/3

**Comment by nergoza** [comment] 2015-02-12 10:20
Hi,
I used --npn-list=spdy/3 and it worked with TLS.
but the performance are really bad - I must use only ECDHE ciphers and the proxy cannot handle more than 30-50 connections /sec.

I set the workers to 100, 500 and even 5000 and it didn't help.

if we could somehow fix the issue when HTTP 1.1 requests are been sent properly as HTTP/2 to the backend server.

Because it looks like that the proxy ignores the --max-http2-concurrent-streams=100 when clients sent multiply requests in HTTP 1.1

**Comment by tatsuhiro-t** [comment] 2015-02-12 14:32
From my local performance tests, nghttpx can handle 1000 connections easily.  The flow control is a limited factor (see the difference with --backend-http2-window-bits=20 and --backend-http2-connection-window-bits=20), but degradation in 30-50 connections is something wrong.
Is the benchmark client properly configured?  From the fact that it only outdated spdy/3 protocol, which is now nobody uses, it could be fairly outdated itself too.  Also backend server may be slow.
Did you see nghttpx CPU usage is bottleneck (i.e., 100%)?  Did you identify where is the bottleneck?

> Because it looks like that the proxy ignores the --max-http2-concurrent-streams=100 when clients sent multiply requests in HTTP 1.1

I could not reproduce this.  It could be client or backend server are badly configured or broken.

**Comment by nergoza** [comment] 2015-02-15 06:44
When I send requests from h2load as HTTP/2 to the proxy with --http2-max-concurrent-streams it works fine on my backend.
When I send it from h2load to the proxy without --http2-max-concurrent-streams - the NGTTPX is not considering the amount of transactions in the same connection and therefore sending EACH transaction as a new connection to the backend making it work as HTTP 1.

**Comment by tatsuhiro-t** [comment] 2015-02-15 07:46
I assume you mean `--max-concurrent-streams` or `-m` option of h2load.
The manual clearly describes its behavior: https://nghttp2.org/documentation/h2load.1.html#cmdoption-m
In short, if you omit the option, h2load only sends 1 stream per session, thereby it acts like good old HTTP/1.1.  If you want to send more streams at once use `-m` option.

**Comment by nergoza** [comment] 2015-02-15 07:49
Yes but my Avalanche client is sending pure HTTP 1 requests - I set it to be max persistence - 5 requests per 1 TCP connection.

but the proxy takes each request from that connection and create a new HTTP / 2 connection in the backend and not taking all the 5 requests and set them to be on the same stream of the HTTP /2

**Comment by tatsuhiro-t** [comment] 2015-02-15 07:54
nghttpx makes HTTP/2 TCP connection to backend per core.  If you set `-n` option to 5, then it posts request to 5 HTTP/2 connection in round robin manner.  Is this your situation?

**Comment by nergoza** [comment] 2015-02-15 08:01
In my backend servers logs I see this:
it gets HTTP2 requests and the proxy forcing the backend server send the response for each request and not stacking the requests and then sends the response.

so it's:
<stream1>
request > response #1
request > response #2
request > response #3
request > response #4
request > response #5 
</stream1>
normal HTTP/2 behavior:
<stream1>
request #1 
request #2 
request #3 
request #4 
request #5
response #1
response #2
response #3
response #4
response #5 
</stream1>

**Comment by tatsuhiro-t** [comment] 2015-02-15 08:06
That is completely fine. The backend server is free to process request as it gets.
It is a wrong assumption that all requests must be interleaved.  It completely depends on the backend server how to process incoming requests.  And as I see it, nghttpx does not force backend server to send response one by one, unless backend server sends SETTINGS with MAX_CONCURRENT_STREAM=1, which it self is a problem of backend server and not nghttpx.

**Comment by nergoza** [comment] 2015-02-15 08:15
the backend server works as a forward which means that whatever the client sents (NGHTTPX) it will work as it asked.

So NGHTTPX looks like it's sending it with MAX_CONCURRENT_STREAM=1 even though it got 5 requests in 1 TCP connection.

and when I set MAX_CONCURRENT_STREAM to be MAX_CONCURRENT_STREAM=100 in NGHTTPX it ignores it since the requests were from HTTP 1 client.

it only worked fine when I worked with TLS and SPDY which sends MAX_CONCURRENT_STREAM=100 by default.

and I cannot use TLS since the performance is really bad

**Comment by tatsuhiro-t** [comment] 2015-02-15 08:23
Did you read my comment?  nghttpx works fine and it does not ignore MAX_CONCURRENT_STREAMS.
I really don't know how to fix this issue.

**Comment by nergoza** [comment] 2015-02-15 08:25
I did read it mate.
So let me ask you this:

if my HTTP 1 client is sending 5 requests in 1 TCP connection as HTTP 1.1 and the proxy is set to work with MAX_CONCURRENT_STREAM=1 and -n 5 as well - it will put all the requests in 1 STREAM or for each request it will have different stream?

**Comment by tatsuhiro-t** [comment] 2015-02-15 08:37
HTTP/1 uses 1 TCP connection exclusively for 1 HTTP request/response, right?
So as you wrote, HTTP/1 client sends 5 requests in 1 TCP connection serially, then nghttpx receives one request and forward to backend, no matter how MAX_CONCURRENT_STREAMS or -n is used.
Finally, backend server sends response to nghttpx and then nghttpx sends back to client.
After first response was received, client issues next HTTP request to nghttpx and things go similarly again.

Probably, you have to use 5 TCP connection and sends HTTP request in each connection from client to make nghtpx send multiple requests to backend in 1 HTTP/2 connection (don't use `-n` option for now).

**Comment by nergoza** [comment] 2015-02-15 08:39
So I need to set in the client that each request is a new TCP connection and set nghttpx MAX_CONCURRENT_STREAM=100 and it put them all in the same stream?

**Comment by tatsuhiro-t** [comment] 2015-02-15 08:47
Set backend server's MAX_CONCURRENT_STREAM=100, not nghttpx.

**Comment by nergoza** [comment] 2015-02-15 08:52
Ok mate - fix your paypal account :)

**Comment by tatsuhiro-t** [comment] 2015-02-15 08:53
Unfortunately, under our country's law, I cannot receive donations via paypal anymore.  I have find another way.

**Comment by nergoza** [comment] 2015-02-17 14:32
Hi,

I did it and still I'm getting request > response, this is from our backend logs:

**Comment by tatsuhiro-t** [comment] 2015-02-17 15:52
I don't see any problem in nghttpx regarding to this matter.  I might be able to say something useful if you show me nghttpx log.

**Comment by nergoza** [comment] 2015-02-18 09:51
You need the -LINFO output?

**Comment by tatsuhiro-t** [comment] 2015-02-18 17:15
Yes

**Comment by nergoza** [comment] 2015-02-23 12:58
Mate, can you please edit all your comments here:
https://github.com/tatsuhiro-t/nghttp2/issues/148

Please remove the word 'Akamai' since it's not an official and Akamai
managers didnt like this :(

**Comment by tatsuhiro-t** [comment] 2015-11-22 14:04
This is old thread.  I close this issue for now.  If you still have this problem, reopen this issue.

**Closed by tatsuhiro-t** 2015-11-22 14:04 UTC
Labels: question
