### ISSUE TITLE
OCSP query command failed

### ISSUE THREAD

**Issue by markcodes** [tatsuhiro-t/nghttp2#254] opened 2015-06-12 10:41 UTC
After installing nghttp2 and running from command line i got the following error:

root@use1proxy:~/nghttp2# nghttpx -f123.123.123.123,443 -b127.0.0.1,8082 /etc/squid3
/ssl/use1proxy.thissite.com.key /etc/squid3/ssl/use1proxy_thissite_com.crt
root@use1proxy:~/nghttp2# 12/Jun/2015:10:30:59 +0000 PID23045 [NOTICE] Listening
 on 123.123.123.123, port 443
12/Jun/2015:10:30:59 +0000 PID23045 [NOTICE] Renew ticket keys: main
fetch-ocsp-response (using OpenSSL 1.0.1f 6 Jan 2014)
--issuer option was not used, and failed to extract issuer certificate from the
certificate
12/Jun/2015:10:30:59 +0000 PID23045 [WARN] shrpx_connection_handler.cc:498 ocsp
query command for /etc/squid3/ssl/use1proxy_thissite_com.crt failed: error=0, rs
tatus=65280, status=255

I've been using the same certificates in shrpx (not running simultaneously with nghttp2) and it is working great, but here on nghttp2 I am having this issue. I am also using absolute path of the certificate.
Anyone have some solution please?

Thanks!

**Comment by tatsuhiro-t** [comment] 2015-06-12 11:10
Is your certificate valid or self-signed?

**Comment by markcodes** [comment] 2015-06-12 18:29
Valid, mine is from Comodo.

**Comment by tatsuhiro-t** [comment] 2015-06-13 07:52
Thanks.  The problem is that nghttpx could not find the certificate of issuers which issued your certificate.
Usually, your certificate is signed by intermediate certificate(s), and they are included in your certificate file, in the order your certificate first, and its issuer's, and so on.  I think probably your certificate file does not include intermediate certificate.  If your certificate is directly issued by root comodo, then it is another story.

**Comment by markcodes** [comment] 2015-06-13 11:53
ok i combined the certificates and got this from command line:

root@use1proxy:/etc/apache2/ssl# 13/Jun/2015:11:47:58 +0000 PID9434 [NOTICE] Lis
tening on 123.123.123.123, port 443
13/Jun/2015:11:47:58 +0000 PID9434 [NOTICE] Renew ticket keys: main
fetch-ocsp-response (using OpenSSL 1.0.1f 6 Jan 2014)
sending OCSP request to http://ocsp.comodoca.com
/etc/apache2/ssl/bundle3.crt: good
        This Update: Jun 12 20:05:00 2015 GMT
        Next Update: Jun 16 20:05:00 2015 GMT

verifying the response signature
verify OK (used: [u'-VAfile', u'/tmp/tmp9V06wk/issuer.crt'])

my config is below:
frontend=123.123.123.123,443
backend=127.0.0.1,8082
private-key-file=/etc/squid3/ssl/use1proxy.thissite.com.key
certificate-file=/etc/squid3/ssl/bundle3.crt
cacert=/etc/squid3/ssl/bundle.pem

ocsp-update-interval=1h
http2-proxy=yes
no-via=yes
daemon=yes


but im getting an error:
This webpage is not available
ERR_SPDY_PROTOCOL_ERROR

**Comment by tatsuhiro-t** [comment] 2015-06-13 11:58
This is chrome bug https://code.google.com/p/chromium/issues/detail?id=433784
Currently, chrome cannot use HTTP/2 proxy.
The workaround is build nghttpx with libspdylay, and use --npn-list=spdy/3.1 to make chrome use SPDY/3.1 instead of HTTP/2.

**Comment by markcodes** [comment] 2015-06-13 12:02
thanks that fixed the issues :D

**Comment by tatsuhiro-t** [comment] 2015-06-13 12:19
OK, let's close the issue.  BTW, Firefox supports HTTP/2 proxy as well.

**Closed by tatsuhiro-t** 2015-06-13 12:19 UTC
