### ISSUE TITLE
h2load errors on http/1.1

### ISSUE THREAD

**Issue by icing** [tatsuhiro-t/nghttp2#372] opened 2015-09-28 08:45 UTC
Anything I can help to find out what is going wrong?
```
Darwin delight.greenbytes.de 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

```
10:42:36 delight:~/projects/httpd/test/mod_h2/trunk> /opt/apache-trunk/bin/h2load -c 1 -t 1 -m 1 -n 500 --npn-list=h2 https://test2.example.org:12346/index.html
starting benchmark...
spawning thread #0: 1 concurrent clients, 500 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 141.50ms, 3533.64 req/s, 6.92MB/s
requests: 500 total, 500 started, 500 done, 500 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 500 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 1026625 bytes total, 15089 bytes headers, 1002500 bytes data
                     min         max         mean         sd        +/- sd
time for request:      202us       521us       251us        34us    89.40%
time for connect:    10.66ms     10.66ms     10.66ms         0us   100.00%
time to 1st byte:    11.18ms     11.18ms     11.18ms         0us   100.00%
10:42:42 delight:~/projects/httpd/test/mod_h2/trunk> /opt/apache-trunk/bin/h2load -c 1 -t 1 -m 1 -n 500 --npn-list=http/1.1 https://test2.example.org:12346/index.html
starting benchmark...
spawning thread #0: 1 concurrent clients, 500 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: http/1.1
progress: 10% done
progress: 20% done

finished in 26.56ms, 3802.42 req/s, 8.16MB/s
requests: 500 total, 102 started, 500 done, 101 succeeded, 399 failed, 399 errored, 0 timeout
status codes: 101 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 227370 bytes total, 20114 bytes headers, 202505 bytes data
                     min         max         mean         sd        +/- sd
time for request:      134us       413us       152us        34us    95.05%
time for connect:    10.79ms     10.79ms     10.79ms         0us   100.00%
time to 1st byte:    11.10ms     11.10ms     11.10ms         0us   100.00%
```

**Comment by tatsuhiro-t** [comment] 2015-09-28 13:28
Thank you for reporting this issue.  Since the number of failed and errored are the same, this means that failure occurred in network level, and not HTTP level in its definition. Still I have to dig into the code what can happen..

**Comment by tatsuhiro-t** [comment] 2015-09-28 13:31
It seems that all errors are counted into both errored and failed in HTTP/1.1 session.  So the failure could be HTTP level.

**Comment by tatsuhiro-t** [comment] 2015-09-28 13:33
OK, I got reproduced the exact the same error.

**Comment by tatsuhiro-t** [comment] 2015-09-28 13:46
I think this is because current h2load treated connection drop as error, and not tries to reconnect to the server if there are requests still to be done.
It seems Apache drops connection after serving 101 requests, if so, this explains the result.

**Comment by icing** [comment] 2015-09-28 13:56
Yes, Apache httpd defaults to 100 requests and then closes the connection (announced). I just set this to unlimited and h2load works fine. 

Thanks for finding that so quickly (again)! ;-)

**Comment by tatsuhiro-t** [comment] 2015-09-28 14:51
Fix committed via 252df2d
h2load does not reuse SSL/TLS session now.  Will be fixed in later commits.

**Comment by tatsuhiro-t** [comment] 2015-09-28 15:00
OK, all done.

**Closed** 2015-11-22 13:57 UTC
Labels: h2load

**Comment by LPardue** [comment] 2016-02-01 14:23
@icing wrote:
> Yes, Apache httpd defaults to 100 requests and then closes the connection (announced). I just set this to unlimited and h2load works fine. 

I'm now seeing similar behaviour after 100 requests. Can you please share how did you fixed this issue in httpd (aka what directive allows me to set it to unlimited)?

P.S sorry for the necromancy!

**Comment by icing** [comment] 2016-02-01 14:24
```
MaxRequestsPerChild 0
```
should do the trick.

**Comment by LPardue** [comment] 2016-02-01 14:34
Hmm, it doesn't seem to address my issue. I am using mpm_event which may make some difference

**Comment by icing** [comment] 2016-02-01 14:38
What you may also see is a setting that limits the amount of connections a process accepts. When reaching this, the process is shut down and another is started. The setting for that is https://httpd.apache.org/docs/2.4/de/mod/mpm_common.html#maxconnectionsperchild

**Comment by LPardue** [comment] 2016-02-01 14:46
I tried setting [MaxKeepAliveRequests](url) to 0 ( and removing `MaxRequestsPerChild`), this addressed the issue I was seeing. 

I have not changed any of the MPM defaults.
