### ISSUE TITLE
"Waiting for proxy tunnel" on Chrome

### ISSUE THREAD

**Issue by nubela** [tatsuhiro-t/nghttp2#267] opened 2015-06-24 09:41 UTC
On regular browsing with SPDY SSL proxy backed by nghttpx + Squid backend, I get random "Waiting for proxy tunnel" by which all tabs will not load until a short while later, then all the tabs will resume loading.

During this lag period, Chrome will say "Waiting for proxy tunnel", but Squid continues to work.

Tatsuhiro says:

"Hanging connection issue may be because of per origin host connection limit nghttpx enforces when making backend connection. Currently, max number of connections per origin host for each frontend connection is limited to 8.

Another possible reason is flow control window is exhausted. This could be checked using chrome net-intetnal."

Tatsuhiro, can you elaborate on what you mean by

* per origin host connection limit nghttpx enforces when making backend connection
* flow control window is exhausted

And what I can do to

1. test which it is
2. mitigate it

Thanks Tatsuhiro!

**Comment by tatsuhiro-t** [comment] 2015-06-24 15:33
When chrome connected to nghttpx via SPDY or HTTP/2, nghttpx allow 100 concurrent streams.
If they are all requests to the same host (e.g., example.com), without per origin connection limit, nghttpx just sends 100 requests to backend squid, and it happily relays 100 requests to the origin, which is too hard for the host.  Since backend connection is HTTP/1.1, we have to do the game in HTTP/1.1 rule.  Web browser uses around 6 connections per origin host.  So nghttpx uses 8 per origin host to avoid excessive amount of traffic to the same host.  You can change this value using --backend-http1-connections-per-host, but I think 8 is good value.  Perhaps, reducing read timeout on backend connection will eagerly close the persistent connection (see --backend-read-timeout).

Open chrome://net-internal, and click HTTP/2 from top-left menu.
You can see HTTP/2 sessions chrome has.
You will see "direct://" in proxy, that is the SPDY connection to the nghttpx proxy.
Check the column "Send window".  If this value gets 0, nghttpx cannot send any data.

Another possibility is running out of max concurrent streams, which 100.  Today, I opened several sites, but does not hit this limit.  But if too many pages and resources are loaded and those connections are all persisted, then theoretically we could hit this limit.  But then I think this should be handled by browser, not proxy, by closing idle connections as necessary.

To my honest, I'm not sure what chrome is doing while it is saying "Waiting for proxy tunnel."
Perhaps, asking for help to chrome developer is also a good idea.

**Comment by nubela** [comment] 2015-06-24 15:37
Let me do some research into this and get back to you.

**Comment by nubela** [comment] 2015-06-24 15:37
If I haven't mentioned, thanks a million again for your help:)

**Comment by tatsuhiro-t** [comment] 2015-06-24 15:49
Perhaps, you can try the workaround described in note section in http://tatsuhiro-t.github.io/spdylay/package_README.html#shrpx-a-reverse-proxy-for-spdy-https

**Comment by tatsuhiro-t** [comment] 2015-06-30 14:09
I tried many times by changing "MaxConnectionsPerProxy" to lower value.  When I set it to 8, I see some "wait for proxy tunnel" message briefly, about 10 seconds, but no more.  Actually, I could not have reproduced longer freeze.

**Comment by tatsuhiro-t** [comment] 2015-07-04 02:15
These chrome bugs may be the cause:
https://code.google.com/p/chromium/issues/detail?id=464875
https://code.google.com/p/chromium/issues/detail?id=473259

In short, they are flow control issue on chrome side.  They say Chrome 44 may have short term workaround.

Using Firefox may be a good workaround for a while, if you can switch to Firefox.. It has different flow control approach.

**Comment by tatsuhiro-t** [comment] 2015-07-04 02:45
I somehow reproduced this issue.  But with very artificial settings.  As discussed in the above mentioned chrome bug, I started 2 downloads, each for 1GiB file.  After some seconds, I paused (not stopped) both.
Then I checked chrome://net-internals/#spdy, and I found that "Receive window" for the connection to the nghttpx proxy was 0.  This means nghttpx could not send any more data on that connection.  This is definitely chrome bug, and most likely that chrome did not tell nghttpx that the downloaded data were not consumed while the downloads were paused.  When this happens, when I tried to open another site, I see "waiting for ...." message.

As mentioned above, Chrome 44 may have short term workaround, but it seems that this issue will still happen, the workaround just lowers the probability.

It seems that Firefox does not suffer from paused downloads, since it just reset the downloads when user paused them, thereby release the window size credit, and Firefox tells nghttpx that all data were consumed.

**Comment by nubela** [comment] 2015-07-04 02:46
Interesting, yes, apparently loading lots of YouTube and pausing them
causes the same issue.

**Comment by tatsuhiro-t** [comment] 2015-07-04 02:54
Thank you for confirmation.  I'm afraid to say that the workaround is not pause youtube or downloads at all.. until Chrome team fixes this issue.  Or move to Firefox.

**Comment by tatsuhiro-t** [comment] 2015-07-04 06:24
@nubela Have you encounter similar issues with Firefox?

**Comment by nubela** [comment] 2015-07-05 06:46
This makes a lot of sense. Opening YouTube videos and pausing them will replicate this issue. 

And no, Firefox is fine.

Perhaps we can close this to be a Chrome's issue?

Looking at https://code.google.com/p/chromium/issues/detail?id=473259 , it seems that there isn't a real fix yet?

**Comment by tatsuhiro-t** [comment] 2015-07-05 09:25
Only short term fix was committed (available in M45?), there seems no concrete long term solution, as far as I read the bug report.

**Closed** 2015-07-05 13:43 UTC

**Comment by nubela** [comment] 2015-07-05 13:44
I'm going to close this issue, because it is not nghttpx's issue.

However, as you mentioned, this is definitely a breaking bug on Chrome. Given that we run SPDY SSL proxies as a service, this bug is fundamentally business-model breaking too.

My team and I will be testing this issue further and updating as we find more information.
