### ISSUE TITLE
URL double entry

### ISSUE THREAD

**Issue by markcodes** [tatsuhiro-t/nghttp2#255] opened 2015-06-13 12:09 UTC
I am running nghttpx or shrpx on a cloud with squid as backend.
When I am using shrpx, I can browse https and http websites using firefox and chrome without any issues.
But when running nghttpx and using firefox i get the following errors:

ERROR
The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: http://yahoo.comhttp://yahoo.com/

    Invalid URL

Some aspect of the requested URL is incorrect.

Some possible problems are:

    Missing or incorrect access protocol (should be "http://" or similar)

    Missing hostname

    Illegal double-escape in the URL-Path

    Illegal character in hostname; underscores are not allowed.

Your cache administrator is webmaster.

as you can see, there is a double url entry on yahoo.com when using nghttpx.

What seem to be the issue?

**Comment by markcodes** [comment] 2015-06-13 12:14
this is the log when accessing "yahoo.com" from firefox:

Jun 13 12:13:30 use1proxy nghttpx[9632]: 37.210.148.219 - - [13/Jun/2015:12:13:3
0 +0000] "GET http://yahoo.comhttp://yahoo.com/favicon.ico HTTP/1.1" 400 3231 "-
" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"
Jun 13 12:13:30 use1proxy nghttpx[9632]: 37.210.148.219 - - [13/Jun/2015:12:13:3
0 +0000] "GET http://yahoo.comhttp://yahoo.com/favicon.ico HTTP/1.1" 400 3231 "-
" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"

**Comment by tatsuhiro-t** [comment] 2015-06-13 13:21
I could not reproduce this.
I assume you are using latest nghttpx, and --http2-proxy --npn-list=spdy/3.1, right?

**Comment by tatsuhiro-t** [comment] 2015-06-13 13:22
What about use of latest Firefox stable 38.0.5?

**Comment by tatsuhiro-t** [comment] 2015-06-13 14:23
I think this was Firefox bug, which was fixed in the latest stable.  I remember I reported this to firefox developer.

**Comment by markcodes** [comment] 2015-06-13 14:25
Yes i have latest nghttpx and using http2-proxy as well as spdy/3.1.
When i get home i will test on latest firefox.

**Comment by tatsuhiro-t** [comment] 2015-06-13 14:39
OK.  FYI, this is firefox bugzilla entry https://bugzilla.mozilla.org/show_bug.cgi?id=1107881
See also https://github.com/tatsuhiro-t/nghttp2/issues/187, which discussed the same issue.

**Comment by markcodes** [comment] 2015-06-13 18:27
Ok, updating to firefox 38 did fix the problem.

**Closed** 2015-06-15 12:20 UTC
