### ISSUE TITLE
Work with HAProxy 

### ISSUE THREAD

**Issue by nutinshell** [tatsuhiro-t/nghttp2#343] opened 2015-09-06 03:05 UTC
I have haproxy as TLS terminator and nghttpx with --frontend-no-tls as backend, but no real IP pass to squid, can you add support to [haproxy's proxy protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt), like: https://github.com/bumptech/stud/pull/81 , so we can have real client's IP pass to squid proxy.

**Comment by tatsuhiro-t** [comment] 2015-09-06 04:37
Do you have any idea about which proxy protocol version should be supported in nghttpx, version 1 or 2?
Certainly supporting both is optimal, but we have limited resource, so if we can choose one of them, we will do it first.

**Comment by nutinshell** [comment] 2015-09-06 05:22
Cool! I think version 1 should be enough :)

**Comment by alagoutte** [comment] 2015-09-06 07:39
I think it is better to implement version 2 and it is more easy (binary protocol...)

**Comment by tatsuhiro-t** [comment] 2015-09-06 07:48
V2's binary nature is fascinating because it is easier to implement.
The thing is it is not adopted by many:

h2o supports proxy protocol version 1 only (https://h2o.examp1e.net/configure/base_directives.html).
AWS supports proxy protocol version 1 only (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html).
According to https://trac.nginx.org/nginx/ticket/355, nginx supports v1 only.

**Comment by alagoutte** [comment] 2015-09-06 08:03
Yes, it is the problem... (I interesting to have some pcap for implement on @wireshark )

**Comment by tatsuhiro-t** [comment] 2015-09-06 09:05
OK, so we first implement v1 because of its popularity.
That is sad.  When I implemented memcached client in nghttpx, I went straight to binary protocol version, since it is a lot easier.

**Comment by tatsuhiro-t** [comment] 2015-09-06 12:31
First cut of PROXY protocol version 1 implementation #344

**Comment by tatsuhiro-t** [comment] 2015-09-07 14:54
PR #344 has just merged.  Use --accept-proxy-protocol to enable PROXY protocol support.

**Comment by ruzarowski** [comment] 2015-09-16 21:24
Hi, we are using the latest release of nghttpx in conjunction with haproxy.
After configuring haproxy to use the proxy protocol in tcp mode
to pass the requests to nghttpx the whole thing simply stopped to work
with these errors in nghttpx error log (log-level already set to INFO):

```
16/Sep/2015:23:17:49 +0200 PID4208 [INFO] shrpx_connection_handler.cc:257 [LISTEN:0x7faa988c51c0] Accepted connection. fd=9
16/Sep/2015:23:17:49 +0200 PID4208 [INFO] shrpx_client_handler.cc:889 [CLIENT_HANDLER:0x7faa98923000] PROXY-protocol: Started
16/Sep/2015:23:17:49 +0200 PID4208 [INFO] shrpx_client_handler.cc:1059 [CLIENT_HANDLER:0x7faa98923000] PROXY-protocol-v1: Finished, 50 bytes read
16/Sep/2015:23:17:49 +0200 PID4208 [INFO] shrpx_connection.cc:394 tls: handshake is still in progress
16/Sep/2015:23:18:19 +0200 PID4208 [INFO] shrpx_connection.cc:281 tls: handshake read error
16/Sep/2015:23:18:19 +0200 PID4208 [INFO] shrpx_client_handler.cc:418 [CLIENT_HANDLER:0x7faa98923000] Deleting
16/Sep/2015:23:18:19 +0200 PID4208 [INFO] shrpx_client_handler.cc:441 [CLIENT_HANDLER:0x7faa98923000] Deleted
```
This now renders every http/2 request broken and gives the client (browser) a blank page.

Any ideas about what is going wrong in there?

Thanks in advance.

**Comment by tatsuhiro-t** [comment] 2015-09-17 12:33
Does haproxy terminate SSL/TLS?
What if you supply --frontend-no-tls option to nghttpx?
I got the same log if we send PROXY protocol line followed by decrypted HTTP/2 traffic.

**Comment by ruzarowski** [comment] 2015-09-17 12:40
haproxy is not terminating SSL, it just sends the traffic to nghttpx with proxy protocol enabled.
I will try to terminate TLS at haproxy and see if this persists. I'll get back to you on it in an hour or so.

**Comment by ruzarowski** [comment] 2015-09-17 13:12
Hi, there is some good news but also some bad.

Good: terminating SSL at haproxy renders the page usable again over https.
Bad: It is no longer upgrading the connection from my Chrome browser, so it stays at HTTP 1.1 instead of a protocol upgrade to h2. 

Any Ideas about what might be causing this? Maybe decrypting of the traffic at haproxy prevents
nprotocol negotiation? Sorry, I'm by far not as familiar with the protocol specs as you are, so maybe you might shed some light on this issue. The protocol upgrade  feature is a must have for us,
but also having the right X-Forwarder-For is a must have in this case. Thanks in advance.

**Comment by tatsuhiro-t** [comment] 2015-09-17 13:17
I just reproduced this hanging SSL/TLS handshake.  Will look into it.
In order to negotiate application layer protocol, we have to pass through all SSL/TLS traffic to backend, or use separate backend for protocol negotiated via ALPN on haproxy (I just heard this, but never done that before).

**Comment by tatsuhiro-t** [comment] 2015-09-17 13:28
I got the cause, and fixed it.  1c2fcc2 will fix this issue.

**Comment by ruzarowski** [comment] 2015-09-17 13:31
Awesome, lightning fast, thanks!
Will build a Distro package and test it with your commit.
I'll get back to you with a confirmation ASAP.

**Comment by ruzarowski** [comment] 2015-09-17 14:37
Hi,
I can now confirm the commit as working.
We have now haproxy tcp via ProxyProto -> nghttpx -> http backend, ALPN negiotioation and Upgrade to h2 works now AND we have the right x-forwarded-for header in the backend even though haproxy on port 443 is in tcp mode. Exactly what we needed, thanks :)

**Comment by tatsuhiro-t** [comment] 2015-09-21 10:51
Although there is v2 left to be implemented, I think v1 is good enough for the most use cases.
So we'll close this issue.  For v2, please submit new issue.

**Closed by tatsuhiro-t** 2015-09-21 10:51 UTC
